'area: background':
  - changed-files:
      - any-glob-to-any-file: 'src/background/**/*'

'area: ci':
  - changed-files:
      - any-glob-to-any-file: '.github/**/*.yml'

'area: content':
  - changed-files:
      - any-glob-to-any-file: 'src/content/**/*'

'area: pages':
  - changed-files:
      - any-glob-to-any-file: 'src/pages/**/*'

'area: pages/app':
  - changed-files:
      - any-glob-to-any-file: 'src/pages/app/**/*'

'area: pages/notification':
  - changed-files:
      - any-glob-to-any-file: 'src/pages/progress-connect/**/*'

'area: popup':
  - changed-files:
      - any-glob-to-any-file: 'src/pages/popup/**/*'

'area: shared':
  - changed-files:
      - any-glob-to-any-file: 'src/shared/**/*'

'area: documentation':
  - changed-files:
      - all-globs-to-any-file:
          - '**/*.md'
          - '!.github/actions/**/*.md'

'area: scripts':
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**/*'

'area: tests':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.test.tsx'
          - 'tests/**/*'

'area: i18n':
  - changed-files:
      - any-glob-to-any-file: 'src/_locales/**/*'
