'area: server':
  - any:
      - changed-files:
          - any-glob-to-any-file: 'packages/server/src/**/*'

'area: background':
  - any:
      - changed-files:
          - any-glob-to-any-file: 'packages/extension/src/background/**/*'

'area: ci':
  - any:
      - changed-files:
          - any-glob-to-any-file: '.github/**/*.yml'

'area: content':
  - any:
      - changed-files:
          - any-glob-to-any-file: 'packages/extension/src/content/**/*'

'area: popup':
  - any:
      - changed-files:
          - any-glob-to-any-file: 'packages/extension/src/popup/**/*'

'area: documentation':
  - any:
      - changed-files:
          - all-globs-to-any-file:
              - '**/*.md'
              - '!.github/actions/**/*.md'

'area: tests':
  - any:
      - changed-files:
          - any-glob-to-any-file: '**/*.test.ts'
