name: Environment setup
description: Sets up Node and pnpm

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with: { node-version-file: .nvmrc }

    - name: Install PNPM
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

    - name: Setup PNPM cache
      uses: actions/cache@v5
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
