name: Environment setup

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/iron'

    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get PNPM store path
      id: pnpm-cache
      shell: bash
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup PNPM cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
