blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/interledger/web-monetization-extension/discussions
    about: Ask questions and discuss with other community members
