name: Delete PR artifacts

on:
  pull_request:
    types:
      - closed

jobs:
  delete:
    name: Delete artifacts
    if: github.repository == 'interledger/web-monetization-extension'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/actions/delete-artifacts.cjs')
            await script({ github, context, core })
