name: Delete PR artifacts

on:
  pull_request:
    types:
      - closed

jobs:
  delete:
    name: Delete artifacts
    if: github.repository == 'interledger/web-monetization-extension'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Delete artifacts
        uses: actions/github-script@v8
        with:
          script: |
            const { default: script } = await import('./.github/actions/delete-artifacts.ts')
            await script({ github, context, core })
