name: End-to-End Tests
on:
  push:
    branches:
      - main
      - 'v[0-9]+.x'
  pull_request:
    types:
      # Only run when label "e2e-needed" is added to avoid waste
      - labeled
      - unlabeled
    branches:
      - main
      - 'v[0-9]+.x'

jobs:
  check:
    runs-on: ubuntu-22.04
    outputs:
      run: ${{ steps.check.outputs.run }}
    steps:
      - uses: actions/checkout@v4
      - name: Environment setup
        # Even if not needed, setup env to improve cache-hit for next steps
        uses: ./.github/actions/setup

      - name: Check if e2e tests should be run
        uses: actions/github-script@v7
        id: check
        with:
          script: |
            core.setOutput('run', 'true')
            // const script = require('./.github/actions/should-run-e2e-tests.cjs')
            // await script({ github, context, core })

  test:
    needs: check
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Chrome
            project: chrome
            target: chrome
            runs-on: ubuntu-22.04
          # - name: Firefox
          #   project: firefox
          #   target: firefox
          #   runs-on: ubuntu-22.04
          # - name: Edge
          #   project: edge
          #   target: chrome
          #   runs-on: windows-2022

    timeout-minutes: 10
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    if: needs.check.outputs.run == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Environment setup
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build ${{ matrix.target }} --channel=nightly

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm test:e2e --project=${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 3
