name: Check PR title

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize

jobs:
  check-pr-title:
    name: Check PR Title
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Check PR title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request?.title;
            if (!title) {
              throw new Error('Pull request title not found');
            }

            const semanticPattern = /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z -]+\))?: .+/;
            
            if (!semanticPattern.test(title)) {
              throw new Error(
                'Pull request title must follow the semantic commit message format: ' +
                'type(scope): description\n\n' +
                'Examples:\n' +
                '  feat(ui): add new button component\n' +
                '  fix(api): handle null response\n' +
                '  docs: update README'
              );
            }
