name: Check PR title

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize

jobs:
  check-pr-title:
    name: Check PR Title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
